#cloud-config

#Mise a jour de l'os
package_update: true
package_upgrade: true

#Installation de paquet
packages:
  - curl
  - wget
  - vim
  - sudo
  - tmux
  - lsof

#Ajout d'un utilisateur
users:
    - default
    - name: alasta
      groups: [ sudo ]
      shell: /bin/bash
      homedir: /home/alasta
      sudo: ['ALL=(ALL) NOPASSWD:ALL']
      lock_passwd: false
  	  passwd: $6$xyz$VKswtvLoVpOLcpjDMIFXhxa8ukqqKSKHjcPBLZUk9NxWldmlFQY4stUGo.QjEhav7mp86ih2PRqYPqjkhWi5y.
        #ssh_authorized_keydds: #Public keys

fqdn: myhostname.myfqdn
hostname: myhostname

runcmd:
  - touch /tmp/touchtest
  - wget https://raw.githubusercontent.com/alasta/dotfiles/master/.bash_profile -O /home/alasta/.bash_profile
  - wget https://raw.githubusercontent.com/alasta/dotfiles/master/.inputrc -O /home/alasta/.inputrc
  - wget https://raw.githubusercontent.com/alasta/dotfiles/master/.tmux.conf -O /home/alasta/.tmux.conf
  - wget https://raw.githubusercontent.com/alasta/dotfiles/master/.vimrc -O /home/alasta/.vimrc
  - chown -R alasta:alasta /home/alasta/
  - wget https://raw.githubusercontent.com/alasta/dotfiles/master/.bash_profile_root -O ~/.bash_profile
